### PR TITLE
Support for scalar printing without bsg_printf (example in bsg_loader_suite/hello)

### PR DESCRIPTION
**Pull request by max-ruttenberg**
* Host support can be found here: https://github.com/bespoke-silicon-group/bsg_f1/pull/342
* Supports printing signed 32-bit integers in decimal.
* Supports printing unsigned 32-bit integers in decimal.
* Supports printing unsigned 32-bit integers in hexadecimal.
* Supports printing 32-bit floating point numbers.
* Supports printing 32-bit floating point numbers in scientific notation.
* All scalar values are printed with their source tile coordinate.

### CODE REVIEW

**Comment by max-ruttenberg** [comment]
Can this be merged?

**Comment by tommydcjung** [comment]
the latest version is 0.7

**Comment by max-ruttenberg** [comment]
I was told by a higher power to branch from 0.6 explicitly.

**Comment by drichmond** [comment]
Yes, that higher power was me

**Comment by drichmond** [comment]
I was hoping to test this today, and we only have v0.6 working in cosim/F1. Buuuut I got sidetracked by passing arguments to VCS and haven't had a chance yet

**Comment by drichmond** [comment]
Can you retarget this to master?

**Pull request merged**
