### PR TITLE
Removed stale file

### PR DESCRIPTION
**Pull request by drichmond**

### CODE REVIEW

**Comment by tommydcjung** [comment]
also remove it from here?
https://github.com/bespoke-silicon-group/bsg_manycore/blob/22b4591af122bb6b02be4b7b94f5445dc713ee60/v/bsg_manycore_hetero_socket.v#L79

**Comment by drichmond** [comment]
I suppose I should clarify. We don't necessarily need to remove it, but when compiling, this is the error that shows up: 

%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:1: Cannot find include file: bsg_manycore_packet.vh

(And others, which may not be related)

%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:35: Expecting ( to begin argument list for define reference `bsg_manycore_packet_width
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:35: Define passed too many arguments: bsg_manycore_return_packet_width
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:36: Define passed too many arguments: bsg_manycore_link_sif_width
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:55: Define passed too many arguments: declare_bsg_manycore_packet_s
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:192: Extra underscore in meta-comment; use /*synopsys {...}*/ not /*synopsys_{...}*/
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:202: Extra underscore in meta-comment; use /*synopsys {...}*/ not /*synopsys_{...}*/
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:35: syntax error, unexpected '=', expecting ')' or ','
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:53: syntax error, unexpected assign
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:67: syntax error, unexpected IDENTIFIER
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:115: syntax error, unexpected ';', expecting TYPE-IDENTIFIER
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:118: syntax error, unexpected IDENTIFIER
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:134: syntax error, unexpected assign
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:156: syntax error, unexpected IDENTIFIER
%Error: /mnt/users/spin0/no_backup/drichmond/Research/repositories/git/bsg_bladerunner/bsg_manycore/v/bsg_manycore_accel_default.v:193: syntax error, unexpected if

**Comment by taylor-bsg** [comment]
It’s stale code, and maybe could be marked as such. But it demonstrates a certain kind of minimal accelerator, which I am not sure we have the equivalent of elsewhere.

**Comment by drichmond** [comment]
Yeah, that’s why I fixed it up and closed this PR. See my other PR

**Pull request closed without merging**
