### PR TITLE
vcache_atomic_inc_multi

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by drichmond** [comment]
What's the difference between this and other atomic tests? This one is multi-core?

**Comment by tommydcjung** [comment]
This one has multiple locks and multiple data.

**Comment by drichmond** [comment]
Ah, so the other one has multiple cores too?

**Comment by tommydcjung** [comment]
Yes...if there is only one core, what's the point of locking?

**Comment by drichmond** [comment]
Well, could be testing the lock implementation

But yes. I just don't see the tile group commands in the other test. But that's not an issue for this test -- this one looks good.

**Review by drichmond — APPROVED** [review]

**Pull request merged**
