### PR TITLE
Moving axi mem to basejump

### PR DESCRIPTION
**Pull request by dpetrisko**

### CODE REVIEW

**Review by drichmond — APPROVED** [review]

**Comment by drichmond** [comment]
Reroll and I'll merge when the machines build

**Comment by drichmond** [comment]
We good?

**Comment by dpetrisko** [comment]
CI still failing

**Comment by tommydcjung** [comment]
I don't think it's necessary to update this, since in the new version we will not use this memory.

**Comment by drichmond** [comment]
It can always be removed later, but Dan is moving it out for BP (and thankfully) trying to keep CI working at the same time. Modulo some pre-existing failure with CI

**Comment by tommydcjung** [comment]
I just don't want to deal with rebasing conflict for changes that are not necessary.

**Comment by dpetrisko** [comment]
Closing, unnecessary

**Pull request closed without merging**
