### PR TITLE
cache_to_axi use bsg_arb_round_robin

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by tommydcjung** [comment]
Using bsg_arb_round_robin to support num_cache_p beyond 16.

**Comment by taylor-bsg** [comment]
What's the motivation for switching the implementation instead of just upgrading the existing module to handle larger els_p? What are the scaling implications? Which system uses this module? FPGA?

**Comment by dpetrisko** [comment]
https://github.com/bespoke-silicon-group/basejump_stl/pull/305

**Comment by tommydcjung** [comment]
This is used for simulation, if you were to go beyond 16 in actual hw, you wouldn't want to use this module any way. The problem with the old round robin module is that if you want to go beyond 32, then you have to update the module again.

**Comment by drichmond** [comment]
Is this just for simulation? If it is - why not move this file into the testbenches folder (or similar) so that it doesn't accidentally get used in Silicon?

**Comment by taylor-bsg** [comment]
If it is synthesizeable but not scalable, okay just to note it in the
comments — both where it is used and in the implementation.

**Pull request closed without merging**
