### PR TITLE
added some comments in vanilla_core_profiler

### PR DESCRIPTION
**Pull request by tommydcjung**
These comments explain how to gather the statistics requested in #170

### CODE REVIEW

**Comment by drichmond** [comment]
Does this resolve #170?

**Comment by tommydcjung** [comment]
yes, those metrics can be calculated from the existing metrics.

**Comment by drichmond** [comment]
OK, I've amended your description to say this.

**Comment by bornaehsani** [comment]
This is great! thanks a lot Tommy.

**Pull request merged**
