### PR TITLE
Move Manycore Host Interface to (0,0)

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by drichmond** [comment]
Is the first commit from Borna part of this PR?

**Comment by tommydcjung** [comment]
it shouldn't be. I'm not sure how it got in there.

**Comment by drichmond** [comment]
Aren't we getting rid of dev?

**Comment by drichmond** [comment]
And if you didn't want it - why include Borna's PR?

**Comment by tommydcjung** [comment]
It is needed, when I rebased the branch on dev, it was somehow included.
we will get rid of dev, once we do one-time merge from dev to master.

**Pull request merged**
