### PR TITLE
Energy benchmark update

### PR DESCRIPTION
**Pull request by tommydcjung**
energy_lr_aq_test and other updates

### CODE REVIEW

**Comment by drichmond** [comment]
LGTM, but what's the reason for using packets instead of an architecturally idempotent instruction?

**Comment by tommydcjung** [comment]
Because you can't put a bind module on a post-apr netlist to detect this instruction being executed. Non post-apr approach is not accurate.

**Review by drichmond — APPROVED** [review]

**Comment by drichmond** [comment]
Got it, SGTM.

There will be some loss in fidelity, but you know that.

**Comment by tommydcjung** [comment]
That's why it runs many instructions to take an average.

**Pull request merged**
