### PR TITLE
Fixed old file for new manycore parameters

### PR DESCRIPTION
**Pull request by drichmond**

### CODE REVIEW

**Comment by drichmond** [comment]
Instead of removing it in #294, I fixed it.

**Comment by drichmond** [comment]
Can we merge this?

**Comment by tommydcjung** [comment]
I think it makes for sense to remove it from the hetero socket, since it's not going to work functionally or even synthesize correctly. I would say just keep the file for sentimental value, and create an issue to fix it in future.

**Comment by drichmond** [comment]
@taylor-bsg @tommydcjung 

This is blocking verilator progress now. Can we come to a conclusion on the way forward? I've fixed this file but I don't know of any test that checks the functionality.

**Comment by drichmond** [comment]
Should someone be writing a testbench here?

**Comment by taylor-bsg** [comment]
I think it’s okay to just indicate that it has been update to build but has not been tested recently.

**Comment by drichmond** [comment]
OK, I've added a fatal statement in an initial block. If anyone tries to instantiate this module it will fail during simulation -- thereby forcing them to give explicit acknowledgement that this module is untested.

**Comment by drichmond** [comment]
How are we feeling about this? Is my solution acceptable?

**Comment by taylor-bsg** [comment]
LGTM

**Pull request merged**
