### PR TITLE
Fnmadd/sub fix

### PR DESCRIPTION
**Pull request by tommydcjung**
-Fixing fma ops that were swapped for fnmadd/fnmsub.

### CODE REVIEW

**Review by taylor-bsg — APPROVED** [review]
Interesting, so this is basically an Errata in the big chip?

**Comment by taylor-bsg** [comment]
@dpetrisko

**Comment by dpetrisko** [comment]
Hi, I believe the previous behavior was correct (although the name is unintuitive as this ISA manual notes)

image

I think this is verified by the rv32uf-p-fmadd test here: https://github.com/bespoke-silicon-group/bsg_manycore/tree/d47c40d7d9ed16d0f448686147743e875dd5fa02/software/spmd/bsg_riscv_tests

**Comment by tommydcjung** [comment]
Never mind guys, got confused by the document.

**Pull request closed without merging**
