### PR TITLE
Added DPI interface for vanilla_operation_trace.csv

### PR DESCRIPTION
**Pull request by drichmond**
New interface (which is backward compatible, `+trace` still works) allows users to turn tracing on/off from C/C++

For small kernels, this results in a 50% smaller trace file, and at LEAST 94% smaller trace file for kernels with large datasets because the API can eliminate tracing during data transfer. (Or, they can include it. But the user gets to decide now).

I've also added a regression test kernel that performs vector add, and demonstrates the C/C++ API.

### CODE REVIEW

**Comment by tommydcjung** [comment]
Can't the dpi modify trace_en_i coming from top-level?

**Comment by drichmond** [comment]
I thought about that. 

To clarify your question though - Are you suggesting that the DPI modify the signal at the top level? Or drive it internally in themodule.

**Comment by tommydcjung** [comment]
at the top-level

**Comment by drichmond** [comment]
Gotcha, 

I can do that, there is no technical reason I can't. 

I specifically chose this way because I wanted to provide an ability to trace a subset of tiles in the future.

Furthremore, the the DPI interface (and associated class) was already written for this module. This was the simplest path to adding this feature.

One drawback of this approach (as already hinted in my description) is that it doesn't work for vcache tracing. I would need another DPI interface for that.

**Comment by tommydcjung** [comment]
Sure you can also have an array of trace_en_i in the top-level.

**Comment by drichmond** [comment]
That's reasonable. I'm coming around to that approach because I could write a general DPI-GPIO module

**Pull request closed without merging**
