### PR TITLE
helping tip for identifying colors in MacOS

### PR DESCRIPTION
**Pull request by taylor-bsg**

### CODE REVIEW

**Comment by tommydcjung** [comment]
Maybe there should be a mode to assist with color-blindness.

**Comment by taylor-bsg** [comment]
Borna has set it up so you can do your own custom colors; “build the door
frame, not the extra room.”

**Comment by dpetrisko** [comment]
I believe matplotlib/seaborn have a bunch of color sets designed for high contrast as well as being disability-friendly. Perhaps a future enhancement is to support these packs, in addition to custom schemes

**Comment by taylor-bsg** [comment]
I did look a little bit into this. If there is an off-the shelf option
that’s seems adequate that’s great, but apparently from what I read, color
blindness is not standard in terms of what people see, so the
configurability that Borna provides may actually be the best solution.

**Comment by drichmond** [comment]
Everyone has valid points. I see no reason we can't merge this. What's the standard in manycore? Does the submitter merge?

**Comment by tommydcjung** [comment]
It was just a random thought. just merge it?

**Pull request merged**
