### PR TITLE
Added counting and printing number of cycles spent on each basic block to PC histogram

### PR DESCRIPTION
**Pull request by bornaehsani**
Previously we had the number of times each basic block is executed. Now we also count number of cycles spend on the PCs inside that basic block, which includes stalls, mispredicts, and bubbles.
@mrutt92  I believe this covers what you asked for, let me know!

### CODE REVIEW

**Comment by drichmond** [comment]
Can you upload an example?

**Comment by bornaehsani** [comment]
Sample output: 

`PC Block                               Exe Cnt               Block Size      Total Intrs Exe Cnt             Total Cycles
=========================================================================================================================
[00000000 - 00000084]                       16                       34                      544                      560
[00000108 - 00000124]                       16                        8                      128                      128
[00000150 - 000001e8]                       16                       39                      624                     3612
[000001ec - 000001fc]                      128                        5                      640                      640
[00000200 - 00000210]                     1024                        5                     5120                     5120
[00000214 - 0000022c]                    32768                        7                   229376                  1441792
[00000230 - 0000023c]                     1024                        4                     4096                     4096
[00000240 - 00000254]                      128                        6                      768                      768
[00000258 - 00000288]                       16                       13                      208                      208
[0000028c - 000002a0]                     1093                        6                     6558                     6558
[000002a4 - 000002cc]                        8                       11                       88                       88
[000002d0 - 000002e4]                      266                        6                     1596                     1596
[000002e8 - 00000330]                        4                       19                       76                       76
[00000334 - 00000338]                        8                        2                       16                       16
[0000033c - 00000344]                        4                        3                       12                     3327
[00000348 - 00000390]                        8                       19                      152                      152
[00000394 - 00000398]                       16                        2                       32                       32
[0000039c - 000003a0]                        8                        2                       16                    16804
[000003a4 - 000003d8]                       16                       14                      224                      224
[000003f4 - 00000408]                       32                        6                      192                      192
[0000040c - 00000464]                       16                       23                      368                   205649
[000004a0 - 000004a8]                       16                        3                       48                       56
[000004b8 - 000004cc]                       16                        6                       96                       96
[000004d0 - 000004e0]                        4                        5                       20                       20
[000004e4 - 000004e4]                       16                        1                       16                       16
[fffffffc - fffffffc]                     5814                        1                     5814                   364110
`

**Comment by bornaehsani** [comment]
> Can you upload an example?

Sure! Sample output: 

PC Block                               Exe Cnt               Block Size      Total Intrs Exe Cnt             Total Cycles
=========================================================================================================================
[00000000 - 00000084]                       16                       34                      544                      560
[00000108 - 00000124]                       16                        8                      128                      128
[00000150 - 000001e8]                       16                       39                      624                     3612
[000001ec - 000001fc]                      128                        5                      640                      640
[00000200 - 00000210]                     1024                        5                     5120                     5120
[00000214 - 0000022c]                    32768                        7                   229376                  1441792
[00000230 - 0000023c]                     1024                        4                     4096                     4096
[00000240 - 00000254]                      128                        6                      768                      768
[00000258 - 00000288]                       16                       13                      208                      208
[0000028c - 000002a0]                     1093                        6                     6558                     6558
[000002a4 - 000002cc]                        8                       11                       88                       88
[000002d0 - 000002e4]                      266                        6                     1596                     1596
[000002e8 - 00000330]                        4                       19                       76                       76
[00000334 - 00000338]                        8                        2                       16                       16
[0000033c - 00000344]                        4                        3                       12                     3327
[00000348 - 00000390]                        8                       19                      152                      152
[00000394 - 00000398]                       16                        2                       32                       32
[0000039c - 000003a0]                        8                        2                       16                    16804
[000003a4 - 000003d8]                       16                       14                      224                      224
[000003f4 - 00000408]                       32                        6                      192                      192
[0000040c - 00000464]                       16                       23                      368                   205649
[000004a0 - 000004a8]                       16                        3                       48                       56
[000004b8 - 000004cc]                       16                        6                       96                       96
[000004d0 - 000004e0]                        4                        5                       20                       20
[000004e4 - 000004e4]                       16                        1                       16                       16
[fffffffc - fffffffc]                     5814                        1                     5814                   364110

**Comment by bornaehsani** [comment]
> Can you upload an example?

Sure! Sample output:

Capture

**Comment by taylor-bsg** [comment]
Nice feature! What is FFFC?

**Comment by bornaehsani** [comment]
Thanks! I believe it actually isn't a valid PC, it shows up in the traces with multiple types of stalls / instructions, but it is basically the highest word-addressable value that the 32-bit PC can take, so I think it has a special meaning, I'm just not sure what it is. 
In the previous PC histogram version it didn't show up because I limited the valid PC values to be between 0x0000 - 0x2000, anything outside of this range would have been ignored before. However now in the updated PC histogram that I'm processing the entire range of 32-bit PCs, it shows up. @tommydcjung Do you have any idea what it means when the PC is set to the highest possible value?

**Comment by taylor-bsg** [comment]
Did we ever get followup on this?

**Comment by tommydcjung** [comment]
I think that means bubble in the pipeline.

**Comment by bornaehsani** [comment]
Interesting, that makes sense when I compare the number of FFFC instructions executed with the total number of bubble cycles from the stats parser. So looks like we haven't been counting bubble cycles of instructions as part of them. I'm not quite sure though on how to attribute a bubble with an instruction.

**Comment by taylor-bsg** [comment]
Presumably the bubble should be associated with the instruction that it
precedes? But Tommy may have some thoughts.

**Comment by taylor-bsg** [comment]
To clarify, I guess there are two ways to do this; one is to have the
tracking in the RTL bind statement; the other way is to do it based on the
traces. There are benefits to both...

M

**Comment by tommydcjung** [comment]
If it's branch mispredict bubble it should be associated with the branch instruction. If it's stall_depend bubble, then it should be related to the stalled instruction in ID. The existing trace doesn't have that information, so there might be more logics needed in RTL.

**Comment by taylor-bsg** [comment]
At least in this example, it appears that it's needed in order to have an
accurate histogram..

**Pull request merged**
