### PR TITLE
Smaller reentrancy struct to save DMEM space and moved string read-only data to dram

### PR DESCRIPTION
**Pull request by vb000**

### CODE REVIEW

**Comment by drichmond** [comment]
Can you post before/after, just for posterity? (nm output is fine, or a summary)

**Comment by vb000** [comment]
Here's the comparison of new and old pytorch binaries:

```
New disassembly                                                             Old disassembly
(Smaller reentrancy structure & no string read-only data)

 
 kernel.riscv:     file format elf32-littleriscv                             kernel.riscv:     file format elf32-littleriscv
                                                                             
                                                                             
 Disassembly of section .data.dmem:                                          Disassembly of section .data.dmem:
                                                                             
 00001000 <impure_data>:                                                     00001000 <impure_data>:
   ...                                                                           1000:	0000                	unimp
                                                                                 1002:	0000                	unimp
 Disassembly of section .sdata.dmem:                                             1004:	12ec                	addi	x11,x2,364
                                                                                 1006:	0000                	unimp
 000010f0 <__bsg_tile_group_id>:                                                 1008:	1354                	addi	x13,x2,420
     10f0: ffff                  0xffff                                          100a:	0000                	unimp
     10f2: ffff                  0xffff                                          100c:	13bc                	addi	x15,x2,488
                                                                             	...
 000010f4 <__bsg_tile_group_id_y>:                                               10a6:	0000                	unimp
     10f4: ffff                  0xffff                                          10a8:	0001                	nop
     10f6: ffff                  0xffff                                          10aa:	0000                	unimp
                                                                                 10ac:	0000                	unimp
 000010f8 <__bsg_tile_group_id_x>:                                               10ae:	0000                	unimp
     10f8: ffff                  0xffff                                          10b0:	330e                	fld	f6,224(x2)
     10fa: ffff                  0xffff                                          10b2:	abcd                	j	16a4 <_bsg_data_end_addr+0xa4>
                                                                                 10b4:	1234                	addi	x13,x2,296
 000010fc <__bsg_grid_dim_y>:                                                    10b6:	e66d                	bnez	x12,11a0 <tensorlib_eye+0xd4>
     10fc: ffff                  0xffff                                          10b8:	deec                	sw	x11,124(x13)
     10fe: ffff                  0xffff                                          10ba:	0005                	c.nop	1
                                                                                 10bc:	0000000b          	0xb
 00001100 <__bsg_grid_dim_x>:                                                	...
     1100: ffff                  0xffff                                      
     1102: ffff                  0xffff                                      Disassembly of section .sdata.dmem:
                                                                             
 00001104 <__bsg_grp_org_y>:                                                 00001428 <TWO23-0xa4>:
     1104: ffff                  0xffff                                          1428:	0000                	unimp
     1106: ffff                  0xffff                                          142a:	e000                	fsw	f8,0(x8)
                                                                                 142c:	ffff                	0xffff
 00001108 <__bsg_grp_org_x>:                                                     142e:	000047ef          	jal	x15,542e <tensorlib_lossnll_backwar
     1108: ffff                  0xffff                                          1432:	0000                	unimp
     110a: ffff                  0xffff                                          1434:	0000                	unimp
                                                                                 1436:	7ff0                	flw	f12,124(x15)
 0000110c <__bsg_id>:                                                            1438:	0000                	unimp
     110c: ffff                  0xffff                                          143a:	0000                	unimp
     110e: ffff                  0xffff                                          143c:	0000                	unimp
                                                                                 143e:	fff0                	fsw	f12,124(x15)
 00001110 <__bsg_y>:                                                             1440:	0000                	unimp
     1110: ffff                  0xffff                                          1442:	e000                	fsw	f8,0(x8)
     1112: ffff                  0xffff                                          1444:	ffff                	0xffff
                                                                                 1446:	0000c7ef          	jal	x15,d446 <_ZN12_GLOBAL__N_128convol
 00001114 <__bsg_x>:                                                             144a:	0000                	unimp
     1114: ffff                  0xffff                                          144c:	0000                	unimp
     1116: ffff                  0xffff                                          144e:	7ff8                	flw	f14,124(x15)
                                                                                 1450:	0000                	unimp
 00001118 <__fdlib_version>:                                                     1452:	3f80                	fld	f8,56(x15)
     1118: 0002                  c.slli64  x0                                    1454:	ffff                	0xffff
   ...                                                                           1456:	ff7f                	0xff7f
                                                                                 1458:	ffff                	0xffff
 0000111c <_impure_ptr>:                                                         145a:	3f7f                	0x3f7f
     111c: 1000                  addi  x8,x2,32                                  145c:	0000                	unimp
   ...                                                                           145e:	3000                	fld	f8,32(x8)
                                                                                 1460:	0000                	unimp
 00001120 <TWO23>:                                                               1462:	4f00                	lw	x8,24(x14)
     1120: 0000                  unimp                                           1464:	0000                	unimp
     1122: 4b00                  lw  x8,16(x14)                                  1466:	8000                	0x8000
     1124: 0000                  unimp                                           1468:	f2ca                	fsw	f18,100(x2)
     1126: cb00                  sw  x8,16(x14)                                  146a:	7149                	addi	x2,x2,-368
                                                                                 146c:	0000                	unimp
 00001128 <halF>:                                                                146e:	bf80                	fsd	f8,56(x15)
     1128: 0000                  unimp                                           1470:	7180                	flw	f8,32(x11)
     112a: 3f00                  fld f8,56(x14)                                  1472:	42b1                	li	x5,12
     112c: 0000                  unimp                                           1474:	f1b5                	bnez	x11,13d8 <tensorlib_eye+0x30c>
     112e: bf00                  fsd f8,56(x14)                                  1476:	aa3bc2cf          	fnmadd.d	f5,f23,f3,f21,rmm
                                                                                 147a:	3fb8                	fld	f14,120(x15)
 00001130 <ln2HI>:                                                               147c:	7180                	flw	f8,32(x11)
     1130: 7180                  flw f8,32(x11)                                  147e:	3f31                	jal	139a <tensorlib_eye+0x2ce>
     1132: 3f31                  jal 104e <_bsg_data_start_addr+0x4e>            1480:	f7d1                	bnez	x15,140c <tensorlib_eye+0x340>
     1134: 7180                  flw f8,32(x11)                                  1482:	bb4c3717          	auipc	x14,0xbb4c3
     1136: bf31                  j 1052 <_bsg_data_start_addr+0x52>              1486:	3331                	jal	1192 <tensorlib_eye+0xc6>
                                                                                 1488:	ea0e                	fsw	f3,20(x2)
 00001138 <ln2LO>:                                                               148a:	b5dd                	j	1370 <tensorlib_eye+0x2a4>
     1138: f7d1                  bnez  x15,10c4 <_bsg_data_start_addr+0xc4>      148c:	b355                	j	1230 <tensorlib_eye+0x164>
     113a: f7d13717            auipc x14,0xf7d13                                 148e:	388a                	fld	f17,160(x2)
     113e:             auipc x14,0x1000b                                         1490:	0b61                	addi	x22,x22,24
                                                                                 1492:	bb36                	fsd	f13,432(x2)
 00001140 <_global_impure_ptr>:                                                  1494:	3e2aaaab          	0x3e2aaaab
     1140: 1000                  addi  x8,x2,32                                  1498:	0000                	unimp
     1142: 0000                  unimp                                           149a:	4000                	lw	x8,0(x8)
     1144: 0000                  unimp                                           149c:	0000                	unimp
   ...                                                                           149e:	0d80                	addi	x8,x2,720
                                                                                 14a0:	0000                	unimp
 Disassembly of section .init_array:                                             14a2:	cc00                	sw	x8,24(x8)
                                                                                 14a4:	0000                	unimp
 00001148 <.init_array>:                                                         14a6:	4c00                	lw	x8,24(x8)
     1148: b5ac                  fsd f11,104(x11)                                14a8:	3eaaaaab          	0x3eaaaaab
     114a: 0002                  c.slli64  x0                                    14ac:	0000                	unimp
                                                                                 14ae:	3f00                	fld	f8,56(x14)
 Disassembly of section .sbss.dmem:                                              14b0:	3e1cd04f          	fnmadd.q	f0,f25,f1,f7,unknown
                                                                                 14b4:	8e29                	xor	x12,x12,x10
 0000114c <cuda_kernel_not_loaded_val>:                                          14b6:	cccd3e63          	0xcccd3e63
     114c: 0000                  unimp                                           14ba:	3ecc                	fld	f11,184(x13)
   ...                                                                           14bc:	3e178897          	auipc	x17,0x3e178
                                                                                 14c0:	3325                	jal	11e8 <tensorlib_eye+0x11c>
 00001150 <cuda_finish_signal_val>:                                              14c2:	3e3a                	fld	f28,424(x2)
     1150: 0000                  unimp                                           14c4:	4925                	li	x18,9
   ...                                                                           14c6:	3e92                	fld	f29,288(x2)
                                                                                 14c8:	3f2aaaab          	0x3f2aaaab
 00001154 <cuda_finish_signal_addr>:                                         
     1154: 0000                  unimp                                       000014cc <TWO23>:
   ...                                                                           14cc:	0000                	unimp
                                                                                 14ce:	4b00                	lw	x8,16(x14)
 00001158 <cuda_argv_ptr>:                                                       14d0:	0000                	unimp
     1158: 0000                  unimp                                           14d2:	cb00                	sw	x8,16(x14)
   ...                                                                       
                                                                             000014d4 <ln2LO>:
 0000115c <cuda_argc>:                                                           14d4:	f7d1                	bnez	x15,1460 <_Z21hb_tiled_foreach_
     115c: 0000                  unimp                                           14d6:	f7d13717          	auipc	x14,0xf7d13
   ...                                                                           14da:	          	auipc	x14,0x7180b
                                                                             
 00001160 <cuda_kernel_ptr>:                                                 000014dc <ln2HI>:
     1160: 0000                  unimp                                           14dc:	7180                	flw	f8,32(x11)
   ...                                                                           14de:	3f31                	jal	13fa <tensorlib_eye+0x32e>
                                                                                 14e0:	7180                	flw	f8,32(x11)
 00001164 <g_reduction_buffer>:                                                  14e2:	bf31                	j	13fe <tensorlib_eye+0x332>
     1164: 0000                  unimp                                       
   ...                                                                       000014e4 <halF>:
                                                                                 14e4:	0000                	unimp
 Disassembly of section .bss.dmem:                                               14e6:	3f00                	fld	f8,56(x14)
                                                                                 14e8:	0000                	unimp
 00001168 <g_barrier>:                                                           14ea:	bf00                	fsd	f8,56(x14)
   ...                                                                       
                                                                             000014ec <_global_impure_ptr>:
 Disassembly of section .text.dram:                                              14ec:	1000                	addi	x8,x2,32
                                                                             	...
 00000000 <_start>:                                                          
        0: 00000093            li  x1,0                                      000014f0 <__bsg_tile_group_id>:
                                                                                 14f0:	ffff                	0xffff
                                                                                 14f2:	ffff                	0xffff
                                                                             
                                                                             000014f4 <__bsg_tile_group_id_y>:
                                                                                 14f4:	ffff                	0xffff
                                                                                 14f6:	ffff                	0xffff
                                                                             
                                                                             000014f8 <__bsg_tile_group_id_x>:
                                                                                 14f8:	ffff                	0xffff
                                                                                 14fa:	ffff                	0xffff
                                                                             
                                                                             000014fc <__bsg_grid_dim_y>:
                                                                                 14fc:	ffff                	0xffff
                                                                                 14fe:	ffff                	0xffff
                                                                             
                                                                             00001500 <__bsg_grid_dim_x>:
                                                                                 1500:	ffff                	0xffff
                                                                                 1502:	ffff                	0xffff
                                                                             
                                                                             00001504 <__bsg_grp_org_y>:
                                                                                 1504:	ffff                	0xffff
                                                                                 1506:	ffff                	0xffff
                                                                             
                                                                             00001508 <__bsg_grp_org_x>:
                                                                                 1508:	ffff                	0xffff
                                                                                 150a:	ffff                	0xffff
                                                                             
                                                                             0000150c <__bsg_id>:
                                                                                 150c:	ffff                	0xffff
                                                                                 150e:	ffff                	0xffff
                                                                             
                                                                             00001510 <__bsg_y>:
                                                                                 1510:	ffff                	0xffff
                                                                                 1512:	ffff                	0xffff
                                                                             
                                                                             00001514 <__bsg_x>:
                                                                                 1514:	ffff                	0xffff
                                                                                 1516:	ffff                	0xffff
                                                                             
                                                                             00001518 <__fdlib_version>:
                                                                                 1518:	0002                	c.slli64	x0
                                                                             	...
                                                                             
                                                                             0000151c <_impure_ptr>:
                                                                                 151c:	1000                	addi	x8,x2,32
                                                                             	...
                                                                             
                                                                             Disassembly of section .init_array:
                                                                             
                                                                             00001520 <.init_array>:
                                                                                 1520:	8310                	0x8310
                                                                                 1522:	0002                	c.slli64	x0
                                                                             
                                                                             Disassembly of section .sbss.dmem:
                                                                             
                                                                             00001524 <cuda_kernel_not_loaded_val>:
                                                                                 1524:	0000                	unimp
                                                                             	...
                                                                             
                                                                             00001528 <cuda_finish_signal_val>:
                                                                                 1528:	0000                	unimp
                                                                             	...
                                                                             
                                                                             0000152c <cuda_finish_signal_addr>:
                                                                                 152c:	0000                	unimp
                                                                             	...
                                                                             
                                                                             00001530 <cuda_argv_ptr>:
                                                                                 1530:	0000                	unimp
                                                                             	...
                                                                             
                                                                             00001534 <cuda_argc>:
                                                                                 1534:	0000                	unimp
                                                                             	...
                                                                             
                                                                             00001538 <cuda_kernel_ptr>:
                                                                                 1538:	0000                	unimp
                                                                             	...
                                                                             
                                                                             0000153c <g_reduction_buffer>:
                                                                                 153c:	0000                	unimp
                                                                             	...
                                                                             
                                                                             Disassembly of section .bss.dmem:
                                                                             
                                                                             00001540 <g_barrier>:
                                                                             	...
                                                                             
                                                                             Disassembly of section .text.dram:
                                                                             
                                                                             00000000 <_start>:
                                                                                    0:	00000093          	li	x1,0
                                                                                    4:	00000193          	li	x3,0
                                                                                    8:	00000213          	li	x4,0
                                                                                    c:	00000293          	li	x5,0
                                                                                   10:	00000313          	li	x6,0
                                                                                   14:	00000393          	li	x7,0                              

```

**Comment by drichmond** [comment]
So 396 bytes vs 1260 (give or take)? Am I reading this correctly?

**Comment by vb000** [comment]
yes, 360 bytes (0x168) vs 1344 bytes (0x540) to be precise

**Comment by vb000** [comment]
There's some information needed to fully understand the changes. I tried all the knowledge we gained in a doc. Please refer to this to understand more and let me know your comments and questions:

https://docs.google.com/document/d/1PdZVmPxS-jCiZjv6TVn4kjxZqX9FktQJec7gbxXJYEk/edit#

**Comment by drichmond** [comment]
LGTM. -- Are debug symbols maintained?

**Comment by vb000** [comment]
They shouldn't be affected. `-g` with disassembly of `.riscv` is able to inline source code, so debug sections seem to be preserved.

**Pull request merged**
