### PR TITLE
remove defunct spmd test

### PR DESCRIPTION
**Pull request by tommydcjung**
these spmds are remove because
- deprecated, no longer works.
- there is a better test for this.

### CODE REVIEW

**Comment by taylor-bsg** [comment]
Maybe you can be more specific about what tests are replacing these tests?

**Comment by tommydcjung** [comment]
These mostly relate to dram access, vcache, and float. We already have an extensive list of tests to cover those cases.

**Comment by drichmond** [comment]
I agree with @taylor-bsg - more specificity would be helpful. Otherwise, assuming we have replacements for these tests that test the same functionality, this PR looks good to me!

**Comment by tommydcjung** [comment]
float: float_asm_test, float_div, float_math, float_vector
cache, dram: memtest1, memtest9, vcache_bang

**Pull request merged**
