### PR TITLE
Migrate manycore to Basejump 2.0

### PR DESCRIPTION
**Pull request by BrendenPage**
[Basejump 2.0](https://github.com/bespoke-silicon-group/basejump_stl/tree/Basejump_2.0) is a new branch of basejump_stl that updates the handshake interface to be more consistent with our style guide (mainly replacing many ready_i/o signals with ready_and_i/o or ready_then_i/o etc). Additionally, the testing infrastructure has been updated to ensure the correctness of the components.

This PR would set manycore to the 2.0 standard and make the repo compatible with the new I/O list changes.

### CODE REVIEW

**Comment by BrendenPage** [comment]
@dpetrisko

**Comment by dpetrisko** [comment]
Yeah we can squash this one and do the renaming in a second PR. You are right that we don't want to squash the rename with the functional changes

**Review by dpetrisko — APPROVED** [review]
LGTM and works locally!

**Comment by dpetrisko** [comment]
@tommydcjung let me know if there's any breakage, but I tested master base jump with this PR and it's working for basic SPMD regression!

**Pull request merged**
