### PR TITLE
Hb fpu

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by drichmond** [comment]
Is this ready to go? Is the profiling code complete, or should it be in another PR?

**Comment by tommydcjung** [comment]
it is ready.

**Comment by drichmond** [comment]
OK. What about the profiling stuff? Is it done too?

**Comment by tommydcjung** [comment]
Yes, that is included in this PR.

**Comment by drichmond** [comment]
How do I use the profiling?

**Comment by tommydcjung** [comment]
https://github.com/bespoke-silicon-group/bsg_manycore/blob/hb_fpu/software/spmd/bsg_print_stat/main.c

example using bsg_print_stat(); basically, it sends a remote packet to host interface, which triggers all the profiles to print out log file (vcache_profile.log, vanilla_core_profile.log).

**Comment by drichmond** [comment]
Cool

Thanks!

**Comment by tommydcjung** [comment]
should I merge commit or rebase and merge?

**Comment by drichmond** [comment]
Rebase? There’s a lot of commits, but I think they’re important. 

Unless you want to squash some of them…

**Pull request merged**
