### PR TITLE
CI setup

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by tommydcjung** [comment]
Screenshot from 2020-03-07 22-54-55
Make sure this doesn't break.

**Comment by mrutt92** [comment]
So... is this supposed to run whenever a PR is submitted?

**Comment by tommydcjung** [comment]
whenever there is PR "ci_*", and merged to master, as a last line of defense.

**Comment by tommydcjung** [comment]
can this be merged?

**Pull request merged**
