### PR TITLE
bsg_cache word tracking wormhole change

### PR DESCRIPTION
**Pull request by tommydcjung**
- Enabling write-validate cache.
- Updating wormhole test mem, and the testbench,
- Added a new test 'memtest2022'

### CODE REVIEW

**Comment by mrutt92** [comment]
what's up with this pr? looks like it's necessary to keep up to date with master in basejump.

**Review by dpetrisko — APPROVED** [review]
LGTM! 

- Is it worth it to add a parameter for word tracking, or do we feel the hardware overhead is always justified?
- Have we tested with this same changeset except for word_tracking_p(0), from a functionality perspective?

**Comment by taylor-bsg** [comment]
Hi,

I think it would be helpful to have the parameter that allows us to
enable/disable it, so that bsg_cache can still be used even when word
writes are not available in the memory backing store.

**Comment by tommydcjung** [comment]
- Added a machine parameter 'BSG_MACHINE_VCACHE_WORD_TRACKING'.

**Pull request merged**
