### PR TITLE
finer granularity for stall_depend & stall_fp

### PR DESCRIPTION
**Pull request by tommydcjung**

### CODE REVIEW

**Comment by tommydcjung** [comment]
https://github.com/bespoke-silicon-group/bsg_manycore/issues/130

**Comment by tommydcjung** [comment]
if there is nothing objectionable, can you approve so we can merge this?

**Comment by drichmond** [comment]
I think this looks fine to me - but I don't have in-depth experience with the trace outputs. Does this address features that @mrutt92 has asked for in the past?

@mrutt92 Can you comment?

**Comment by mrutt92** [comment]
@drichmond @tommydcjung me too!

**Comment by tommydcjung** [comment]
@mrutt92 does it help with the profiling metrics you are trying to calculate? does the number seems accurate?

**Pull request merged**
