### PR TITLE
Added missing inline

### PR DESCRIPTION
**Pull request by drichmond**
If this file is included in multiple .c files that are independently
compiled into .o files, the linker will complain about duplicate
symbols.

### CODE REVIEW

**Comment by mrutt92** [comment]
What you actually want here is to use "static"

Any function defined in a header file should be marked static for exactly this reason.

Use of inline is not guaranteed to work.

**Comment by drichmond** [comment]
Should all of the functions in the header be static, then?

I just mimic'd the rest of them.

**Comment by mrutt92** [comment]
10000000000% yes

**Comment by mrutt92** [comment]
BTW: I'm not saying inline is wrong, you just also need to mark them static.

**Comment by drichmond** [comment]
Fixed, waiting for CI re-run

**Review by mrutt92 — APPROVED** [review]

**Pull request merged**
