### PR TITLE
Fixed origin location for top and bottom memory systems

### PR DESCRIPTION
**Pull request by drichmond**
The python scripts broke when the origin moved

### CODE REVIEW

**Comment by mrutt92** [comment]
anyway we can inherit those values from the machine makefile instead of hardcoding them into the scripts?

**Comment by drichmond** [comment]
We could parse them as input arguments

**Comment by drichmond** [comment]
OK, fixed. Automatically infer origin from the active tiles

**Comment by drichmond** [comment]
Added comments, and tested on single-tile and full-device CUDA programs.

**Comment by bornaehsani** [comment]
Looks good to me, thanks Dustin! I think this is the best way we can deal with the issue of origin right now, but it banks on the fact that the API starts allocating tiles from the upper left most corner, so we should beware if that ever changes.

**Comment by drichmond** [comment]
Yeah, I'm not a fan of that assumption either. We could put a check / warning in but I haven't thought of what that check/warning would be. Basically if the origin isn't (0,0), (1,0), (0,1) or (1,1)? Or more restrictive - (0, 1) as the way things currently are now. 

But that's effectively hard-coding the origin, which is what this PR is addressing.

**Comment by drichmond** [comment]
This is really only a problem in the stats parser, right?

**Comment by bornaehsani** [comment]
Yeah this is only a problem for the parsers, stats parser, stall graph (maybe) and the pc histogram. I think this will suffice to solve the problem for now, and in the future it's easy to detect if the error pops up again.

**Comment by drichmond** [comment]
See #270 (for CI)

**Pull request closed without merging**
